Controllers/ActorsController.cs
using Microsoft.AspNetCore.Mvc;
using MoviePro.Services.Interfaces;
using System.Threading.Tasks;

namespace MoviePro.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IRemoteMovieService _tmdbMovieService;
        private readonly IDataMappingService _mappingService;

        public ActorsController(IRemoteMovieService tmdbMovieService, IDataMappingService mappingService)
        {
            _tmdbMovieService = tmdbMovieService;
            _mappingService = mappingService;
        }


        public async Task<IActionResult> Details(int id)
        {
            var actor = await _tmdbMovieService.ActorDetailAsync(id);
            actor = _mappingService.MapActorDetail(actor);
            return View(actor);
        }
    }
}

Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using MoviePro.Data;
using MoviePro.Models.Database;
using MoviePro.Models.Settings;
using MoviePro.Services.Interfaces;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MoviePro.Controllers
{
    public class MoviesController : Controller
    {
        private readonly AppSettings _appSettings;
        private readonly ApplicationDbContext _context;
        private readonly IImageService _imageService;
        private readonly IRemoteMovieService _tmdbMovieService;
        private readonly IDataMappingService _tmdbMappingService;

        public MoviesController(IOptions<AppSettings> appSettings, ApplicationDbContext context, IImageService imageService, IRemoteMovieService tmdbMovieService, IDataMappingService tmdbMappingService)
        {
            _appSettings = appSettings.Value;
            _context = context;
            _imageService = imageService;
            _tmdbMovieService = tmdbMovieService;
            _tmdbMappingService = tmdbMappingService;
        }

        public async Task<IActionResult> Import()
        {
            var movies = await _context.Movie.ToListAsync();
            return View(movies);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Import(int id)
        {
            //If we already have this movie we can just warn the user instead of importing it again
            if (_context.Movie.Any(m => m.MovieId == id))
            {
                var localMovie = await _context.Movie.FirstOrDefaultAsync(m => m.MovieId == id);
                return RedirectToAction("Details", "Movies", new { id = localMovie.Id, local = true });
            }

            //Step 1: Get the raw data from the API
            var movieDetail = await _tmdbMovieService.MovieDetailAsync(id);

            //Step 2: Run the data through a mapping procedure
            var movie = await _tmdbMappingService.MapMovieDetailAsync(movieDetail);

            //Step 3: Add the new movie
            _context.Add(movie);
            await _context.SaveChangesAsync();

            //Step 4: Assign it to the default All Collection
            await AddToMovieCollection(movie.Id, _appSettings.MovieProSettings.DefaultCollection.Name);

            return RedirectToAction("Import");

        }

        public async Task<IActionResult> Library()
        {
            var movies = await _context.Movie.ToListAsync();

            return View(movies);
        }

        [HttpGet]
        public async Task<IActionResult> Search(string searched)
        {

            List<Movie> movies = new List<Movie>();
            List<Movie> actorMovies = new List<Movie>();
            List<Movie> allMovies = await _context.Movie.ToListAsync();

            // Goes through all movies
            foreach (Movie movie in allMovies)
            {
                if (movie.Cast.Any(m => m.Name.ToLower() == searched.ToLower()))
                {

                    actorMovies.Add(movie);

                }

                else if(movie.Title == searched)
                {
                    movies.Add(movie);
                }
            }

            
            List<Movie> fullList = movies.Union(actorMovies).ToList();

            if(fullList.Count == 0)
            {
                return NotFound();
            }

            else
            {
                if(fullList.Count > 0)
                {
                    return View(fullList);
                }

                return NotFound();
            }


        }

        public async Task<IActionResult> Details(int? id, bool local = false)
        {
            if (id == null)
            {
                return NotFound();
            }

            Movie movie = new();
            if (local)
            {
                movie = await _context.Movie.Include(m => m.Cast)
                                            .Include(m => m.Crew)
                                            .FirstOrDefaultAsync(m => m.Id == id);
            }

            else
            {

                var movieDetail = await _tmdbMovieService.MovieDetailAsync((int)id);
                movie = await _tmdbMappingService.MapMovieDetailAsync(movieDetail);
            }

            if (movie == null)
            {
                return NotFound();
            }

            ViewData["Local"] = local;
            return View(movie);
        }

        public IActionResult Create()
        {
            ViewData["CollectionId"] = new SelectList(_context.Collection, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,MovieId,Title,TagLine,Overview,RunTime,ReleaseDate,Rating,VoteAverage,Poster,PosterType,Backdrop,BackdropType,TrailerUrl")] Movie movie, int collectionId)
        {
            if (ModelState.IsValid)
            {
                movie.PosterType = movie.PosterFile?.ContentType;
                movie.Poster = await _imageService.EncodeImageAsync(movie.PosterFile);
                movie.BackdropType = movie.BackdropFile?.ContentType;
                movie.Backdrop = await _imageService.EncodeImageAsync(movie.BackdropFile);

                _context.Add(movie);
                await _context.SaveChangesAsync();
                await AddToMovieCollection(movie.Id, collectionId);

                return RedirectToAction("Index", "MovieCollections");
            }
            return View(movie);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,MovieId,Title,TagLine,Overview,RunTime,ReleaseDate,Rating,VoteAverage,Poster,PosterType,Backdrop,BackdropType,TrailerUrl")] Movie movie)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (movie.PosterFile is not null)
                    {
                        movie.PosterType = movie.PosterFile.ContentType;
                        movie.Poster = await _imageService.EncodeImageAsync(movie.PosterFile);
                    }
                    if (movie.BackdropFile is not null)
                    {
                        movie.BackdropType = movie.BackdropFile.ContentType;
                        movie.Backdrop = await _imageService.EncodeImageAsync(movie.BackdropFile);
                    }


                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }

                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Id))
                    {
                        return NotFound();
                    }

                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction("Details", "Movies", new { id = movie.Id, local = true });
            }

            return View(movie);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.Movie.FindAsync(id);
            _context.Movie.Remove(movie);
            await _context.SaveChangesAsync();
            return RedirectToAction("Library", "Movies");
        }

        private bool MovieExists(int id)
        {
            return _context.Movie.Any(e => e.Id == id);
        }

        private async Task AddToMovieCollection(int movieId, string collectionName)
        {
            var collection = await _context.Collection.FirstOrDefaultAsync(c => c.Name == collectionName);
            _context.Add(
                new MovieCollection()
                {
                    CollectionId = collection.Id,
                    MovieId = movieId
                }
            );
            await _context.SaveChangesAsync();
        }

        private async Task AddToMovieCollection(int movieId, int collectionId)
        {
            _context.Add(
                new MovieCollection()
                {
                    CollectionId = collectionId,
                    MovieId = movieId
                }
            );
            await _context.SaveChangesAsync();
        }



    }
}

Views/Movies/Details.cshtml
@using MoviePro.Models.Database
@using MoviePro.Services.Interfaces
@inject IImageService _imageService
@model Movie


<div class="row">
    <div class="col-sm-12 col-md-6">
        <div class="row">
            <img src="@_imageService.DecodeImage(Model.Poster, Model.PosterType)" class="w-100" alt="...">
        </div>

        <div class="row">
            <button class="btn btn-lg btn-block btn-danger font-weight-bold" data-toggle="modal"
                    data-target="#trailer">
                WATCH TRAILER
            </button>
        </div>
    </div>

    <div class="col-sm-12 col-md-6">
        <div class="row">
            <div class="col h5">
                <span class="font-weight-bolder mr-2">TITLE:</span> @Model.Title
            </div>
        </div>
        <hr />

        <div class="row">
            <div class="col h5">
                <span class="font-weight-bolder mr-2">RELEASED:</span> @Model.ReleaseDate.ToString("MMM dd, yyyy")
            </div>
        </div>
        <hr />

        <div class="row">
            <div class="col h5">
                <span class="font-weight-bolder mr-2">RATING:</span> @Model.Rating
            </div>
        </div>
        <hr />

        <div class="row">
            <div class="col h5">
                <span class="font-weight-bolder mr-2">REVIEWS:</span> @Model.VoteAverage / 10
            </div>
        </div>
        <hr />

        <div class="row mt-3 mb-2">
            <div class="col">
                <span class="h5 font-weight-bolder"> OVERVIEW:</span>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <span class="h5 ml-4">@Model.Overview</span>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col">
        <span class="h5 font-weight-bolder"> STARRING:</span>
    </div>
</div>

@foreach (var actor in Model.Cast.Take(5))
{
    <div class="row">
        <div class="col">
            <div class="card mb-3">
                <div class="row no-gutters">
                    <div class="col-md-2">
                        <img src="@actor.ImageUrl" class="img-fluid" style="width: 10rem" alt="...">
                    </div>
                    <div class="col-md-10">
                        <div class="card-body">
                            <h5 class="card-title"><a asp-action="Details" asp-controller="Actors" asp-route-id="@actor.CastID">Name: @actor.Name</a></h5>
                            <p class="card-text">Character: @actor.Character</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<!-- Modal -->
<div class="modal fade" id="trailer" tabindex="-1" role="dialog" aria-labelledby="trailerLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">@Model.Title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="embed-responsive embed-responsive-16by9">
                    @{
                        //I am isolating a piece of data in order to use it as my embed source
                        var key = Model.TrailerUrl.Split("=").Last();
                        var source = $"https://www.youtube.com/embed/{key}";
                    }

                    <iframe width="560" height="315" src="@source" 
                            title="YouTube video player" frameborder="0" 
                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
                            allowfullscreen></iframe>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

Views/Movies/Search.cshtml
@using MoviePro.Models.Database
@model List<Movie>

@{
    ViewData["Title"] = "MoviePro";
}

<div>
    <h3>Search Results</h3>
    @foreach (Movie movie in @Model)
    {
        <div class="col-4 mb-2">
            <div class="card" style="width: 18rem;">
                <img src="@movie.Poster" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title clampTitle">@movie.Title</h5>
                    <p class="card-text clampOverview">@movie.Overview</p>
                    <a asp-action="Details" asp-controller="Movies" asp-route-id="@movie.Id" class="btn btn-lg btn-block btn-warning font-weight-bold">Details</a>
                </div>
            </div>
        </div>
    }
</div>